website8/home/urls.py
from django.urls import path
from.import views
app_name='home'

urlpatterns = [
    
    path('', views.get_index),
    path('form/', views.get_formsv.as_view, name='form'),
]

website8/website8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]
urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

website8/home/models.py
from django.db import models

TITLE_CHOICES = (
('PM01', 'Pm01.'),
('PM02', 'Pm02.'),
('IOT', 'IoT.'),
)

# Create your models here.
class svModel(models.Model):
    name = models.CharField(max_length=255)
    mssv = models.CharField(max_length=10)
    birth_day = models.DateField(blank=True, null=True)
    lop = models.CharField(max_length=5, choices=TITLE_CHOICES)
    image = models.ImageField()
    
    def __str__(self):
        return self.lop

website8/home/forms.py
from django import forms
from .models import svModel
class svform(forms.ModelForm):
    class Meta:
        model = svModel
        fields = ['name', 'mssv', 'birth_day', 'lop', 'image' ]

website8/home/views.py
from django.shortcuts import render
from .forms import svform
from django.views import View
from django.http import HttpResponse
from .models import svModel

# Create your views here.
def get_index(request):
    auF = svModel.objects.all()
    return render(request, 'home/index.html',{'auF':auF})

class get_formsv(View):
    def get(self, request):
        svF = svform
        return render(request, 'home/formsv.html', {'svF':svF})
    def post(self, request):
        form = svform(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('Save File success!')
        else:
            return HttpResponse('Save File Failed!')

website8/home/templates/home/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block webtitle %}{% endblock webtitle %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {% block webcontent %}{% endblock  %}
    </body>
</html>

website8/home/templates/home/formsv.html
{% extends "home/base.html" %}
{% block webtitle %}
Welcome Sinh viên form!
{% endblock %}
{% block webcontent %}
<h1> Welcome Sinh viên form! </h1>
<form action="{% url 'home:form' %}" method="POST">
{% csrf_token %}
<table>
{{svF.as_table}}
</table>
<input type="submit">
</form>
{% endblock%}

website8/home/templates/home/index.html
{% extends "home/base.html" %}
{% block webtitle %}
Thông tin sinh viên!
{% endblock %}
{% block webcontent %}
<h1> THÔNG TIN SINH VIÊN! </h1>
<table border="1">
<tr>
<th> Họ tên SV </th>
<th> MSSV </th>
<th> Ngày sinh </th>
<th> Lớp </th>
<th> Hình </th>
</tr>
{% for i in auF %}
<tr>
<td> {{i.name}} </tb>
<td> {{i.mssv}} </td>
<td> {{i.birth_day}} </td>
<td> {{i.lop}} </td>
<td> {{i.image}} </td>
</tr>
{% endfor%}
</table>
{% endblock%}